#!/bin/sh

OPTFILES="globals.cmx vector.cmx mass.cmx particles.cmx camera.cmx drawing.cmx input.cmx driver.cmx main.cmx"

#OPTLIBS="str.cmxa unix.cmxa nums.cmxa bigarray.cmxa sdl.cmxa sdlloader.cmxa sdlttf.cmxa sdlmixer.cmxa"

OPTLIBS="bigarray.cmxa sdl.cmxa sdlloader.cmxa sdlmixer.cmxa sdlttf.cmxa lablgl.cmxa lablglut.cmxa unix.cmxa threads.cmxa"

OCAMLCP=ocamlcp
OCAMLOPT=ocamlopt

OCAMLSDLLIB=`ocamlfind query sdl`

OUTNAME=archer


$OCAMLOPT -thread -o $OUTNAME -I $OCAMLSDLLIB -I +lablGL $OPTLIBS $OPTFILES

